### ISSUE TITLE
Production compilation error when upgrading from v8

### ISSUE THREAD

**Issue by hashwin** [shakacode/react_on_rails#977]
I am trying to migrate my app from v8.0.6, I followed this guide: https://github.com/shakacode/react_on_rails/blob/master/docs/basics/upgrading-react-on-rails.md

I've made the changes and everything works fine in development.

But, when I try to deploy to heroku (or run ```rake assets:precompile```), I get this webpacker error:
```
Webpack binstubs not found.
Have you run rails webpacker:install ?
Make sure the bin directory or binstubs are not included in .gitignore
Exiting!
```

**Comment by justin808** [comment]
@hashwin a recent update fixes this issue. It was caused by webpacker 3.0.2 (from 3.0.1).
