### PR TITLE
Guard preload links for older Shakapacker

### LINKED ISSUE #4369: [Core] react_on_rails_preload_links crashes with NoMethodError on Shakapacker < 8.4 — config.integrity called unguarded
## Summary

The new `react_on_rails_preload_links` helper hard-crashes with `NoMethodError: undefined method 'integrity'` on every Shakapacker version before 8.4. Three private helpers (`preload_source_integrity`, `preload_crossorigin`, `preload_link_attributes`) call `Shakapacker.config.integrity` unguarded, but `Shakapacker::Configuration#integrity` only exists since Shakapacker v8.4.0 (SRI support, shakacode/shakapacker#570, released 2024-09-08). The gemspec allows `shakapacker >= 6.0`, and the helper's only version gate is `nested_entries?` (a 7.0+ feature), so any app on Shakapacker 7.0–8.3 that adopts this documented helper crashes on first render.

## Affected code

- Helper entry point — only gate is `nested_entries?`:
  https://github.com/shakacode/react_on_rails/blob/39e66bda58de24019372e1d663626873baeabff0/react_on_rails/lib/react_on_rails/helper.rb#L243-L254
- `preload_link_attributes` — runs for both JS and CSS links, calls `preload_source_integrity` unconditionally and reads `config.integrity[:cross_origin]` directly:
  https://github.com/shakacode/react_on_rails/blob/39e66bda58de24019372e1d663626873baeabff0/react_on_rails/lib/react_on_rails/helper.rb#L592-L599
- `preload_source_integrity` — first `config.integrity` call reached on every source:
  https://github.com/shakacode/react_on_rails/blob/39e66bda58de24019372e1d663626873baeabff0/react_on_rails/lib/react_on_rails/helper.rb#L612-L616
- `preload_crossorigin` — reached for every modulepreload link even with integrity disabled:
  https://github.com/shakacode/react_on_rails/blob/39e66bda58de24019372e1d663626873baeabff0/react_on_rails/lib/react_on_rails/helper.rb#L618-L621
- Gemspec allows Shakapacker `>= 6.0`:
  https://github.com/shakacode/react_on_rails/blob/39e66bda58de24019372e1d663626873baeabff0/react_on_rails/react_on_rails.gemspec#L45
- Docs state no Shakapacker version floor for the helper:
  https://github.com/shakacode/react_on_rails/blob/39e66bda58de24019372e1d663626873baeabff0/docs/oss/api-reference/view-helpers-api.md#L53-L79

## Introduced in

PR #3935 ("Add preload link helper for generated component packs"), merged 2026-06-11 (`83e582fb7`), in the v16.6.0..43ed0e138 release slice.

## Mechanism

Call chain: `react_on_rails_preload_links` → `preload_link_for_source` → `preload_link_for_javascript_source` / `preload_link_for_stylesheet_source` → `preload_link_attributes` (L592) → `preload_source_integrity` (L612). Line 613 evaluates `current_shakapacker_instance.config.integrity[:enabled]` before any feature check. On Shakapacker < 8.4, `Shakapacker::Configuration` has no `integrity` method (confirmed against the shakapacker CHANGELOG: SRI landed in v8.4.0 via PR shakacode/shakapacker#570), so this raises `NoMethodError` immediately. Even if that call were guarded, `preload_link_for_javascript_source` (L581) calls `preload_crossorigin` (L618–621) for every modulepreload asset, which also reads `config.integrity[:cross_origin]` unconditionally — including when SRI is disabled.

The only gate on the helper is `ReactOnRails::PackerUtils.nested_entries?` (L244), which passes on Shakapacker 7.0+. Nothing checks for 8.4.

## Failure scenario

1. App runs Shakapacker 7.x or 8.0–8.3 (all allowed by the gemspec).
2. App upgrades react_on_rails 16.6 → 17.0 and adopts the documented new helper: `<%= react_on_rails_preload_links("ProductPage") %>` in the layout `<head>`.
3. First page render raises `NoMethodError: undefined method 'integrity' for an instance of Shakapacker::Configuration` from `preload_source_integrity` — a 500 on every page using the layout.

## Impact

- Hard crash (500) on first render for any Shakapacker 7.0–8.3 user adopting the helper — a documented headline feature of the 17.0 release.
- `docs/oss/api-reference/view-helpers-api.md` gives no version floor, so users have no way to anticipate this.
- The error message (`NoMethodError` deep in a private helper) gives no hint that the fix is upgrading Shakapacker.

## Suggested fix

- In `preload_source_integrity` and `preload_crossorigin` (and the direct read in `preload_link_attributes`), guard with `current_shakapacker_instance.config.respond_to?(:integrity)`:
  - When unavailable, skip the `integrity`/`crossorigin` attributes entirely (plain preload links still work and are correct), or alternatively raise a clear error: "react_on_rails_preload_links integrity attributes require Shakapacker >= 8.4".
- Document the behavior/floor in `docs/oss/api-reference/view-helpers-api.md` (helper works on 7.0+ with nested entries; SRI/crossorigin attributes require 8.4+).

## Test plan

- Unit spec for `react_on_rails_preload_links` with a stubbed Shakapacker config object that does **not** respond to `integrity` (simulating < 8.4): helper renders plain preload/modulepreload links without raising.
- Existing specs with `integrity` available continue to pass (attributes emitted when `[:enabled]` is true, `crossorigin` fallback logic unchanged).
- Spec covering the modulepreload path (`preload_crossorigin`) with integrity unavailable.

## Notes

- The every-render FOUC path (`generated_stylesheet_hrefs_json` in `react_on_rails/lib/react_on_rails/pro_helper.rb:50`, from #4047) reuses `preload_sources_for_stylesheet_pack` from this slice but only extracts hrefs — it never reaches the integrity calls. The crash is confined to the opt-in `react_on_rails_preload_links` helper.
- Dupe-checked against #4310–#4360: no existing issue covers this. #3889 (closed) is the feature request that produced #3935.

_Found in the pre-June-12 backfill review of the 17.0.0 release diff (v16.6.0..43ed0e138), verified against current main. Filed by Claude Code on behalf of Justin Gordon._

### PR DESCRIPTION
**Pull request by justin808**
## Summary
- guard React on Rails preload-link SRI helpers when Shakapacker does not expose `config.integrity`
- keep preload hints rendering for Shakapacker versions before integrity settings existed
- document the compatibility behavior in the view helpers API reference and changelog

## Rationale
Issue #4369 affects apps on Shakapacker versions before the integrity configuration API: preload helpers can raise instead of emitting preload links. This PR treats missing integrity configuration as SRI disabled, preserving preload output while keeping existing SRI behavior for newer Shakapacker versions.

Fixes #4369.

## Tests
- `cd react_on_rails/spec/dummy && bundle exec rspec spec/helpers/react_on_rails_helper_spec.rb:139`
- `cd react_on_rails && BUNDLE_GEMFILE=../Gemfile bundle exec rubocop`
- `pnpm exec prettier --check docs/oss/api-reference/view-helpers-api.md`
- `pnpm exec prettier --check CHANGELOG.md`
- `git diff --check origin/main...HEAD`
- `codex review --base origin/main` (no findings)

- `pnpm exec prettier --check CHANGELOG.md docs/oss/api-reference/view-helpers-api.md docs/oss/building-features/performance-tracks-and-profiling.md`
- `lychee --config .lychee.toml docs/oss/building-features/performance-tracks-and-profiling.md`
- pre-push branch lint: RuboCop on branch Ruby files and online Lychee on branch Markdown files

## Codex Decision Log
- **Non-blocking:** Whether the stale ShakaPerf markdown link cleanup belongs in this PR.
  - **Decision:** Keep the one-line de-linking in this PR.
  - **Why:** Hosted `markdown-link-check` failed on the branch because the linked public repository returned 404; fixing that stale link was necessary to recover current-head hosted checks after the #4369 docs change.
  - **Review later:** None.

- **Non-blocking:** Whether missing Shakapacker integrity configuration should suppress all crossorigin attributes.
  - **Decision:** Only suppress SRI-derived `integrity` and configured `crossorigin`; keep existing modulepreload/browser preload behavior where applicable.
  - **Why:** Older Shakapacker has no integrity API, but preload links still need to render compatibly.
  - **Review later:** None.

## Batch A
- Workflow config: UNKNOWN repo-local `.agents/agent-workflow.yml` and `.agents/workflows/pr-processing.md` absent; used installed PR-processing workflow.
- QA lane: required, owner `qa/batch-a`, pending final batch QA.
- Changelog: included in `CHANGELOG.md`.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved preload link handling so links remain compatible with older builds when integrity settings aren’t available, avoiding errors and omitting unsupported security attributes.
  * Preload links still include the expected loading and cross-origin behavior.

* **Documentation**
  * Clarified preload/SRI behavior in the API reference.
  * Updated setup guidance wording in the performance profiling docs.

* **Chores**
  * Updated the changelog with the compatibility fix.

### CODE REVIEW

File: docs/oss/building-features/performance-tracks-and-profiling.md [hunk 1]
```diff
@@ -124,7 +124,7 @@ Then:
    you above it.
 4. Report a **Wilcoxon signed-rank p-value**; treat **p < 0.05** as strong directional evidence of a real shift when the paired samples consistently move in the same direction.
 
-We use [ShakaPerf](https://github.com/shakacode/shakaperf) for this — it brings up the twin production-local servers and runs the paired comparison with `shaka-perf compare --categories perf`. The methodology is what matters, not the tool: any harness that runs two production builds side by side under identical mobile throttling with paired sampling and a significance test gives you the same signal.
+We use ShakaPerf for this — it brings up the twin production-local servers and runs the paired comparison with `shaka-perf compare --categories perf`. The methodology is what matters, not the tool: any harness that runs two production builds side by side under identical mobile throttling with paired sampling and a significance test gives you the same signal.
```
[the remark this answers is not in the document]
Comment (justin808) [reply docs/oss/building-features/performance-tracks-and-profiling.md:127]: Updated the PR description with the reason this is bundled here: this stale public link was failing the branch's hosted `markdown-link-check`, so the one-line de-linking was a current-head CI repair for this PR rather than unrelated docs cleanup.

File: react_on_rails/lib/react_on_rails/helper.rb [hunk 2]
```diff
@@ -610,16 +610,23 @@ def preload_manifest_source(source)
...
+      cross_origin = shakapacker_integrity_config[:cross_origin]
       cross_origin.nil? ? "anonymous" : cross_origin
     end
 
+    def shakapacker_integrity_config
+      config = current_shakapacker_instance.config
+      return {} unless config.respond_to?(:integrity)
+
+      config.integrity || {}
+    end
```
[the remark this answers is not in the document]
Comment (justin808) [reply react_on_rails/lib/react_on_rails/helper.rb:628]: [auto-deferred]
This is a non-blocking optimization nit and the current helper calls only read the Shakapacker config object; adding memoization now would restart review/CI for no correctness change. I’m leaving this as-is for this compatibility fix.
