### PR TITLE
Ignore Arrays in Rails i18n yml files

### LINKED ISSUE #1126: Regression due to PR #1046 ?
Hi, the PR #1046 caused a regression on my end.

In our translations we have arrays in keys like day_names, month_names and so on. Those are for Rails and I'm pretty sure we don't use them in our react app, but they make our build crash:

```
14:35:31 client.1 | rake aborted!
14:35:31 client.1 | NoMethodError: undefined method `gsub' for #<Array:0x00005654df390550>
14:35:31 client.1 | /home/vianney/.rbenv/versions/2.3.6/gemsets/oneparkweb/gems/react_on_rails-11.0.10/lib/react_on_rails/locales_to_js.rb:112:in `block in flatten'
14:35:31 client.1 | /home/vianney/.rbenv/versions/2.3.6/gemsets/oneparkweb/gems/react_on_rails-11.0.10/lib/react_on_rails/locales_to_js.rb:107:in `each'
14:35:31 client.1 | /home/vianney/.rbenv/versions/2.3.6/gemsets/oneparkweb/gems/react_on_rails-11.0.10/lib/react_on_rails/locales_to_js.rb:107:in `each_with_object'
14:35:31 client.1 | /home/vianney/.rbenv/versions/2.3.6/gemsets/oneparkweb/gems/react_on_rails-11.0.10/lib/react_on_rails/locales_to_js.rb:107:in `flatten'
```

Don't tell me I have to split our translation files into "server only" and "server + client" ones... :cold_sweat:

### PR DESCRIPTION
**Pull request by vcarel**
Fixes #1126

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/1129)

### CODE REVIEW

**Comment by justin808** [comment]
@vcarel any update?

**Comment by vcarel** [comment]
@justin808 I'm on vacation for 2 weeks. I'll look into that when I'll be back in. Thx for your review.

**Comment by vcarel** [comment]
@justin808 I just did the update, sorry for the delay.

**Comment by justin808** [comment]
@vcarel can you please rebase on top of master and ensure that CI passes.

**Comment by justin808** [comment]
Thanks @vcarel!
