### ISSUE TITLE
Regression due to PR #1046 ?

### ISSUE THREAD

**Issue by vcarel** [shakacode/react_on_rails#1126]
Hi, the PR #1046 caused a regression on my end.

In our translations we have arrays in keys like day_names, month_names and so on. Those are for Rails and I'm pretty sure we don't use them in our react app, but they make our build crash:

```
14:35:31 client.1 | rake aborted!
14:35:31 client.1 | NoMethodError: undefined method `gsub' for #<Array:0x00005654df390550>
14:35:31 client.1 | /home/vianney/.rbenv/versions/2.3.6/gemsets/oneparkweb/gems/react_on_rails-11.0.10/lib/react_on_rails/locales_to_js.rb:112:in `block in flatten'
14:35:31 client.1 | /home/vianney/.rbenv/versions/2.3.6/gemsets/oneparkweb/gems/react_on_rails-11.0.10/lib/react_on_rails/locales_to_js.rb:107:in `each'
14:35:31 client.1 | /home/vianney/.rbenv/versions/2.3.6/gemsets/oneparkweb/gems/react_on_rails-11.0.10/lib/react_on_rails/locales_to_js.rb:107:in `each_with_object'
14:35:31 client.1 | /home/vianney/.rbenv/versions/2.3.6/gemsets/oneparkweb/gems/react_on_rails-11.0.10/lib/react_on_rails/locales_to_js.rb:107:in `flatten'
```

Don't tell me I have to split our translation files into "server only" and "server + client" ones... :cold_sweat:

**Comment by vcarel** [comment]
```
    def flatten(translations)
      translations.each_with_object({}) do |(k, v), h|
        if v.is_a? Hash
          flatten(v).map { |hk, hv| h["#{k}.#{hk}".to_sym] = hv }
        else
          h[k] = v.gsub("%{", "{")
        end
      end
    end
```

**Comment by justin808** [comment]
Please submit a pr with the appropriate tests.

**Comment by vcarel** [comment]
Hi, 

The unit tests don't pass on my computer:
![image](https://user-images.githubusercontent.com/1541093/43887115-18d1d218-9bbe-11e8-868d-6e154c90c7bc.png)

Besides `rake examples:gen_all` (as mentionned in CONTRIBUTING.md) doesn't work as well.
![image](https://user-images.githubusercontent.com/1541093/43887249-7b06a850-9bbe-11e8-8350-ecb33e179f67.png)

(I did `bundle install` FYI)
Can you help?

I'm was on Ruby 2.5.1 and node v10.8.0.

I can do the PR anyway if you wish, but without adding unit test...

**Comment by justin808** [comment]
@vcarel please try your best.

**Comment by vcarel** [comment]
@justin808 my apologies if my first previous message sounded rude. However if you want to attract contributors you should at least prov
I'm new to Ruby and don't know anything about react_on_rails. But I do know how too look at a stack trace. I'm not interested in spending the day fixing a gemset.

**Comment by vcarel** [comment]
@justin808 My apologies if my previous message sounded rude. Is there a specific Ruby version I should install? What about node.js? Do you think I miss some development libs on my computer?

I would be happy to contribute, really, but at least I would like to do it properly, on a working setup, doing the unit tests first. It would not help you to submit a PR with _untested_ code.

**Comment by justin808** [comment]
I'd try with the latest ruby and node versions. That should work.

**Comment by vcarel** [comment]
okay, I have something which _almost_ works with Node LTS (8.x). I was on Node 10, and it's not supported by node-sass (4.5.3 -> need upgrade to ^4.8.0) - and perhaps others libs... ?

Besides I have an issue with @patrickkettner/get-cursor-position, on which node-gyp get hung quite long at every test. All in all, it takes almost 10 mins to run all the unit tests in this configuration:
```
$ time rake --trace -v
[...]
rake --trace -v  51,73s user 9,80s system 10% cpu 9:38,63 total
```

I have been notified at my side that we have pairing issues with our provider, which could explain why it's that slow. But I would recommend however to move the deps installation (bundler and yarn) out the tests.  But that's not the topic of this issue.

Moreover, I confirm that `rake examples:gen_all` fails a missing coffee-rails error:
```
cd /home/vianney/src/OnePark/react_on_rails/gen-examples/examples/basic && rake webpacker:install
Could not find gem 'coffee-rails (~> 4.2)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
```

And after installing coffee-rails manually, it fails later:

```
cd /home/vianney/src/OnePark/react_on_rails/gen-examples/examples/basic && rake webpacker:install
rake aborted!
Don't know how to build task 'webpacker:install' (see --tasks)
```

Anyway, at the end, I have been able to pass `rake run_rspec` :smile: 

So the fix was very easy compared to the above - here it is: #1129
