### PR TITLE
Feature/no request context

### PR DESCRIPTION
**Pull request by eacaps**
I recently moved our project from browserify to webpack using your tutorial. Great job on that! However I ran into an issue when attempting to use the react_component helper inside an actionmailer. The react_on_rails_helper.rb rails_context method expects to always come from a context that has a request. Unfortunately this is not the case when creating an e-mail via an ActionMailer. I did some basic modifications of react_on_rails_helper.rb to mitigate this issue and included a full test case in your test suite to handle this. You can see what was happening earlier by checking out this [commit](https://github.com/eacaps/react_on_rails/commit/05d3144a99c09d4d86a205d8b2be4edfbe177d1e) and running the tests. I'm obviously open to some tweaks to my implementation of rails_context since right now if there's no request it will just return an empty object.

Thanks again for your great work on react_on_rails, hopefully this will help.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react_on_rails/486)

### CODE REVIEW

**Comment by justin808** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[app/helpers/react_on_rails_helper.rb, line 348 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/486#-KNFdkTMCjMulRELxdrD:-KNFdkTMCjMulRELxdrE:2073927540) ([raw file](https://github.com/shakacode/react_on_rails/blob/6fdb73a5600bb1e4602df4b1c0a0ea914c3107eb/app/helpers/react_on_rails_helper.rb#L348)):*
> ```Ruby
>     @rails_context ||= begin
>       result = {}
>       unless request.nil?
> ```

how about

```ruby
if request.present?
```

---

*[spec/dummy/app/mailers/dummy_mailer.rb, line 4 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/486#-KNFduK_0c0Rkmy1tVup:-KNFduKaXoesNJmh6mgm:667096707) ([raw file](https://github.com/shakacode/react_on_rails/blob/6fdb73a5600bb1e4602df4b1c0a0ea914c3107eb/spec/dummy/app/mailers/dummy_mailer.rb#L4)):*
> ```Ruby
>   add_template_helper(ReactOnRailsHelper)
>   default from: "nobody@nope.com"
>   # layout 'mailer'
> ```

what is this comment?

---

*[spec/dummy/app/views/dummy_mailer/hello_email.html.erb, line 7 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/486#-KNFdzJxWqsutuBJxeUI:-KNFdzJxWqsutuBJxeUJ:1962522967) ([raw file](https://github.com/shakacode/react_on_rails/blob/6fdb73a5600bb1e4602df4b1c0a0ea914c3107eb/spec/dummy/app/views/dummy_mailer/hello_email.html.erb#L7)):*
> ```erb
>         name: "Mr. Mailing Server Side Rendering"
>     }
> }, prerender: true) %>
> ```

needs line return -- see the red symbol

---

*[spec/dummy/config/initializers/react_on_rails.rb, line 5 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/486#-KNFeEYL_iN2OYcJ9BeI:-KNFeEYL_iN2OYcJ9BeJ:-1336327210) ([raw file](https://github.com/shakacode/react_on_rails/blob/6fdb73a5600bb1e4602df4b1c0a0ea914c3107eb/spec/dummy/config/initializers/react_on_rails.rb#L5)):*
> ```Ruby
>   # all calls to react_component and redux_store for rendering
>   def self.custom_context(view_context)
>     result = {}
> ```

could we do this without a rescue?

is there something in view_context that tells us we're in a mailer. This is the Rails API. Introspect on view_context in the debugger, like in pry.

We also need to update the docs on the railsContext for this case, and in general for this fix. We should put in some flag that we're in mailer, like 

```ruby
{
  mailer: true | false;
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/486)*

**Comment by justin808** [comment]
Nice job @eacaps! Some comments! 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/486#-:-KNFf5G3JKHZ6iiAsK6s:-1930000924)*

**Comment by eacaps** [comment]
@justin808 I've made the first few tweaks you recommended. The last suggestion relates to a special custom_context that was already being added to the dummy tester. I tried several ways to get around using a rescue block but nothing really seems to work properly (.try, .respond_to, etc..). Accessing session from view_context uses a delegate from the ActionView::Helpers::ControllerHelper and since the base ActionMailer does not have a session method you end up with: undefined method `session' for #<DummyMailer:0x007fe1c8e58f10>. Since this is in the testing code and not the actual library I felt okay leaving the rescue block in there, but if anyone has another suggestion please feel free to make it.

As far as improving the railsContext in this particular case those changes would be made in the react_on_rails_helper.rb in the rails_context method. The first thought that comes to mind would be   changing the initial result to be

` result = {
  mailer: self.controller.kind_of?(ActionMailer::Base)
}`

I haven't actually implemented that yet, but let me know if that all makes sense.

**Comment by eacaps** [comment]
Also I found this ancient rails issue related to ActionMailer delegation: https://github.com/rails/rails/issues/15613. No action since 2014 but it describes the issue.

**Comment by justin808** [comment]
Let's go with a property called `inMailer`, as `mailer` sounds like more than a boolean.

Maybe to avoid the exception, we can have the customization of the railsContext check this inMailer flag?

happy hacking! this is looking good!

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[spec/dummy/config/initializers/react_on_rails.rb, line 5 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/486#-KNFeEYL_iN2OYcJ9BeI:-KNKCpc88JJCR8SvSH3I:1782231571) ([raw file](https://github.com/shakacode/react_on_rails/blob/9b958fb8d5db9f5792f49a38182991b85c873a8f/spec/dummy/config/initializers/react_on_rails.rb#L5)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> could we do this without a rescue?
> 
> is there something in view_context that tells us we're in a mailer. This is the Rails API. Introspect on view_context in the debugger, like in pry.
> 
> We also need to update the docs on the railsContext for this case, and in general for this fix. We should put in some flag that we're in mailer, like 
> 
> ```ruby
> {
>   mailer: true | false;
> }
> ```
</details>
@eacaps Did you get a chance to hack on this, to figure out from the view_context as to when we're in a mailer? This is something we should document.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/486#-:-KNKDCEmM3D5Va8Oj8kJ:-1878508685)*

**Comment by justin808** [comment]
Looking good!

Please squash your commits and address the following issues.

be sure that `rake lint` passes, as well as the full test suite `rake`

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[app/helpers/react_on_rails_helper.rb, line 347 \[r4\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/486#-KNdjzImgfxrbeJj7ifU:-KNdjzImgfxrbeJj7ifV:380611048) ([raw file](https://github.com/shakacode/react_on_rails/blob/566d62f8166f8a525ec8b83dd973cdf65f6240ba/app/helpers/react_on_rails_helper.rb#L347)):*
> ```Ruby
>   def rails_context(server_side:)
>     @rails_context ||= begin
>       result = { inMailer: controller.present? && controller.is_a?(ActionMailer::Base) }
> ```

Did this pass the linter? I'd probably rather see this on 3 lines.

---

*[app/helpers/react_on_rails_helper.rb, line 365 \[r4\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/486#-KNdkACxtwEu3r-Henq9:-KNdkACxtwEu3r-HenqA:-1817546045) ([raw file](https://github.com/shakacode/react_on_rails/blob/566d62f8166f8a525ec8b83dd973cdf65f6240ba/app/helpers/react_on_rails_helper.rb#L365)):*
> ```Ruby
> 
>           # Locale settings
>           i18nLocale: I18n.locale,
> ```

can we move the `I18n` parts to outside the `request.present?` block?

---

*[spec/dummy/app/mailers/dummy_mailer.rb, line 4 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/486#-KNFduK_0c0Rkmy1tVup:-KNdkNsfe0o7UD8AgNTm:5173665) ([raw file](https://github.com/shakacode/react_on_rails/blob/9b958fb8d5db9f5792f49a38182991b85c873a8f/spec/dummy/app/mailers/dummy_mailer.rb#L4)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> what is this comment?
</details>
OK

---

*[spec/dummy/app/views/dummy_mailer/hello_email.html.erb, line 7 \[r1\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/486#-KNFdzJxWqsutuBJxeUI:-KNdkP__XcJl-9bqspxQ:5173665) ([raw file](https://github.com/shakacode/react_on_rails/blob/9b958fb8d5db9f5792f49a38182991b85c873a8f/spec/dummy/app/views/dummy_mailer/hello_email.html.erb#L7)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> needs line return -- see the red symbol
</details>
OK

---

*[spec/dummy/config/initializers/react_on_rails.rb, line 12 \[r4\]](https://reviewable.io:443/reviews/shakacode/react_on_rails/486#-KNdkiTWfCIP2VeKzfJQ:-KNdkiTWfCIP2VeKzfJR:-684850311) ([raw file](https://github.com/shakacode/react_on_rails/blob/566d62f8166f8a525ec8b83dd973cdf65f6240ba/spec/dummy/config/initializers/react_on_rails.rb#L12)):*
>    result = {}
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>     unless view_context.controller.is_a?(ActionMailer::Base)
>       result = {
>         somethingUseful: view_context.session[:something_useful]
>       }
</details>
>  
>  
>     end
>     result

how about

```ruby
if view_context.controller.is_a?(ActionMailer::Base)
  {}
else
    {
        somethingUseful: view_context.session[:something_useful]
      }
    end
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/486#-:-KNdl1PHYnB5EBHJF5oE:-1349620550)*

**Comment by justin808** [comment]
@eacaps Any update?

**Comment by eacaps** [comment]
I was having some trouble squashing my commits correctly; it seemed to work in another test branch I created but this one wasn't doing it properly. Perhaps because I merged master in a couple times? I was using this link: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html. If you know what I need to do I can try again, or we could close this pull request and open one with a squashed branch. Let me know.

**Comment by justin808** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react_on_rails/486#-:-KO9ls6mGttFoUVzr6t_:980077423)*

**Comment by justin808** [comment]
Hi @eacaps! Looking good.

I think the easiest way to squash is to do a `git merge --squash` over to a new branch, then once you see the branch is correct (tests pass, etc.), delete the original branch, then rename the new branch to the original branch name. Then do a force push.

Please see https://github.com/shakacode/react_on_rails/blob/master/CONTRIBUTING.md for a checklist of things to do.

I noticed that we're missing the changelog entry.

Thanks!

**Comment by eacaps** [comment]
I successfully squashed things into a new branch, but in the process this pull request closed on me. I don't know if its possible for you to reopen this or if I need to submit a new pull request?

**Comment by Xeboc** [comment]
I'm now getting a NameError 'undefined local variable or method 'controller', Did you mean? controller_path' from [react_on_rails_helper.rb#L348](https://github.com/shakacode/react_on_rails/blob/master/app/helpers/react_on_rails_helper.rb#L348) after upgrading to 6.1.0.  This is for a `render app: hydrate_data` call in my app/controllers/pages_controller.rb file, and a `html = react_component(component, props: data)` in my config/initializers/app_renderer.rb file.

**Comment by justin808** [comment]
@eacaps This was already merged in #509

**Comment by Xeboc** [comment]
I'm getting a: 
```
'NameError in PagesController#index' 
undefined local variable or method `controller' for #<PagesController:0x007f022cf7fed8>
Did you mean? controller_path
```
After upgrading to 6.1.0 from 6.0.5.  The framework trace points to this line: [348](https://github.com/shakacode/react_on_rails/pull/486/files#diff-741e57aaaefab9559b7892657ec8c75eR348)
```
+        inMailer: controller.present? && controller.is_a?(ActionMailer::Base),
```

config/initializer/app_renderer.rb
```
ActionController.add_renderer(:app) do |data, options|
  self.extend ReactOnRailsHelper
  self.extend ActionView::Helpers::TagHelper

  component = options.fetch(:component, 'App')
  html = react_component(component, props: data)
  render(options.merge(inline: html))
end
```

app/controllers/pages_controller.rb
```
class PagesController < ApplicationController
  def index
    render app: hydrate_data
  end
end
```

Maybe I'm missing something or using the tooling wrong?

**Comment by justin808** [comment]
@Xeboc what version of Rails. The code works with with 4.x and 5.x Rails.

**Comment by Xeboc** [comment]
Rails 5.0.0.1

**Comment by justin808** [comment]
@Xeboc I'll need you to dig into this further. I'm happy to take a PR if you've got an issue.

**Comment by Xeboc** [comment]
I'll dig, and if looks like it needs a PR, I'll make one.  I wanted to share with you and @eacaps to see if you had any input.  Sometimes code and errors just need another set of eyes for someone to go "Oh, look!  Right there!  Change that!", or to make a slight tweak on their end for robustness.  Thank you for the project and the work you've put into it.

**Comment by justin808** [comment]
@Xeboc Big thanks! My team is slammed with helping our paying. We are available for modestly priced coaching packs if anybody is interested: http://www.shakacode.com/work/.
